title: Kalleb Abreu
description: Data Scientist Portfolio 
# logo: /assets/img/headshot_circle.png
#description: text below image
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
